import {
  Copy,
  Save,
  Play,
  Brain,
  FileCode,
  Loader2,
  Sparkles,
  Keyboard,
  X,
  RotateCcw,
} from "lucide-react";
import { useState, useEffect, useRef } from "react";
import Editor from "@monaco-editor/react";
import Terminal from "./Terminal";
import CodeGenerator from "./CodeGenerator";
import { executeCode, fetchLanguages } from "../../services/codeAPI";
import { getCompletion } from "../../services/aiAPI";
import "./Terminal.css";

const detectLanguage = (filename) => {
  if (!filename) return "javascript";
  const ext = filename.split(".").pop()?.toLowerCase();
  const map = {
    js: "javascript",
    jsx: "javascript",
    ts: "typescript",
    tsx: "typescript",
    py: "python",
    java: "java",
    cpp: "cpp",
    c: "c",
    cs: "csharp",
    rb: "ruby",
    go: "go",
    rs: "rust",
    php: "php",
    swift: "swift",
    kt: "kotlin",
    sql: "sql",
    html: "html",
    css: "css",
    scss: "scss",
    json: "json",
    xml: "xml",
    yaml: "yaml",
    yml: "yaml",
    md: "markdown",
    sh: "shell",
    bash: "shell",
  };
  return map[ext] || "javascript";
};

const formatLangName = (name) => {
  if (!name) return "";
  return name.replace(/\s*\(.*\)\s*/, "").trim();
};

function CodeEditor({ activeFile, project, onContentChange, onOpenAI, runTrigger }) {
  const [isSaved, setIsSaved] = useState(true);
  const [editorContent, setEditorContent] = useState("");
  const [language, setLanguage] = useState("javascript");
  const [selectedCode, setSelectedCode] = useState("");
  const [showTerminal, setShowTerminal] = useState(false);
  const [terminalOutput, setTerminalOutput] = useState("");
  const [terminalError, setTerminalError] = useState("");
  const [isExecuting, setIsExecuting] = useState(false);
  const [executionTime, setExecutionTime] = useState(0);
  const [exitCode, setExitCode] = useState(null);
  const [memory, setMemory] = useState(null);
  const [isCompleting, setIsCompleting] = useState(false);
  const [showGenerator, setShowGenerator] = useState(false);
  const [stdinInput, setStdinInput] = useState("");
  const [showStdin, setShowStdin] = useState(false);
  const [languages, setLanguages] = useState([]);
  const [runCount, setRunCount] = useState(0);
  const editorRef = useRef(null);
  const stdinRef = useRef(null);

  useEffect(() => {
    fetchLanguages().then(setLanguages);
  }, []);

  useEffect(() => {
    if (runTrigger > 0 && project?.files) {
      const mainFile = project.files.find((f) => f.isMain);
      if (mainFile) {
        const mainLang = detectLanguage(mainFile.name);
        setLanguage(mainLang);
        setEditorContent(mainFile.content);
        handleExecute(mainFile.content, mainLang);
      } else {
        alert("No main file set. Right-click a file in the explorer and set it as main.");
      }
    }
  }, [runTrigger]);

  useEffect(() => {
    if (activeFile) {
      setEditorContent(activeFile.content);
      setLanguage(detectLanguage(activeFile.name));
      setIsSaved(true);
      setSelectedCode("");
    }
  }, [activeFile]);

  const handleContentChange = (newContent) => {
    if (newContent !== undefined) {
      setEditorContent(newContent);
      setIsSaved(false);
      onContentChange(newContent);
      setIsSaved(true);
    }
  };

  const handleInsertGeneratedCode = (code) => {
    setEditorContent(code);
    onContentChange(code);
    setIsSaved(false);
  };

  const handleEditorMount = (editor, monaco) => {
    editorRef.current = editor;

    editor.onDidChangeCursorSelection((e) => {
      const selection = editor.getModel().getValueInRange(e.selection);
      setSelectedCode(selection || "");
    });

    monaco.languages.registerCompletionItemProvider(language, {
      triggerCharacters: [".", "(", "{", "[", " ", "\n"],
      provideCompletionItems: async (model, position) => {
        setIsCompleting(true);
        const textUntilPosition = model.getValueInRange({
          startLineNumber: 1,
          startColumn: 1,
          endLineNumber: position.lineNumber,
          endColumn: position.column,
        });
        const textAfterPosition = model.getValueInRange({
          startLineNumber: position.lineNumber,
          startColumn: position.column,
          endLineNumber: model.getLineCount(),
          endColumn: model.getLineMaxColumn(model.getLineCount()),
        });

        try {
          const result = await getCompletion(model.getValue(), language, textUntilPosition, textAfterPosition);
          if (result.success && result.completion) {
            return {
              suggestions: [
                {
                  label: "ai-completion",
                  kind: monaco.languages.CompletionItemKind.Snippet,
                  insertText: result.completion,
                  insertTextRules: monaco.languages.CompletionItemInsertTextRule.None,
                  detail: "AI Suggestion",
                  documentation: "Generated by ZecoAI",
                  range: {
                    startLineNumber: position.lineNumber,
                    startColumn: position.column,
                    endLineNumber: position.lineNumber,
                    endColumn: position.column,
                  },
                },
              ],
            };
          }
        } catch (err) {
          console.error("AI completion failed:", err);
        } finally {
          setIsCompleting(false);
        }
        return { suggestions: [] };
      },
    });
  };

  const handleExecute = async (code, lang) => {
    const codeToRun = code || editorContent;
    const langToUse = lang || language;

    if (!codeToRun.trim()) {
      alert("No code to execute");
      return;
    }

    setShowTerminal(true);
    setIsExecuting(true);
    setTerminalOutput("");
    setTerminalError("");
    setExecutionTime(0);
    setExitCode(null);
    setMemory(null);

    const startTime = Date.now();

    try {
      const result = await executeCode(codeToRun, langToUse, stdinInput);
      const elapsed = ((Date.now() - startTime) / 1000).toFixed(2);
      setExecutionTime(elapsed);
      setExitCode(result.exitCode);
      setMemory(result.memory);
      setRunCount((c) => c + 1);

      if (result.success) {
        setTerminalOutput(result.output || "Code executed successfully with no output");
        setTerminalError("");
      } else {
        setTerminalError(result.error || "Execution failed");
        setTerminalOutput(result.output || "");
      }
    } catch (err) {
      setTerminalError(err.message || "Unknown error occurred");
      setTerminalOutput("");
    } finally {
      setIsExecuting(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(editorContent);
  };

  const handleSave = () => {
    setIsSaved(true);
  };

  const handleClearStdin = () => {
    setStdinInput("");
    stdinRef.current?.focus();
  };

  if (!activeFile) {
    return (
      <div className="flex-1 flex items-center justify-center bg-zinc-950">
        <div className="text-center">
          <FileCode size={48} className="text-white/20 mx-auto mb-3" />
          <p className="text-white/40 text-sm font-medium">No file selected</p>
          <p className="text-white/25 text-xs mt-1">Choose a file from the explorer</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 flex flex-col min-h-0 overflow-hidden">
      {/* ── Toolbar ── */}
      <div className="h-11 min-h-[44px] shrink-0 border-b border-zinc-800 px-4 flex items-center justify-between gap-3 bg-zinc-950">
        {/* Left: File info */}
        <div className="flex items-center gap-2.5 min-w-0">
          <FileCode size={15} className="text-zinc-500 shrink-0" />
          <span className="text-[13px] font-semibold text-zinc-200 truncate">{activeFile.name}</span>
          {!isSaved && <span className="w-1.5 h-1.5 rounded-full bg-amber-400 shrink-0" />}
          <span className="text-[11px] text-zinc-600 hidden sm:inline">/ {project?.name}</span>
        </div>

        {/* Right: Actions */}
        <div className="flex items-center gap-1">
          {isCompleting && (
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-purple-500/10 text-purple-400 text-[11px] font-medium mr-1">
              <Loader2 size={12} className="animate-spin" />
              <span className="hidden md:inline">AI...</span>
            </div>
          )}

          {/* Language Selector */}
          <select
            value={language}
            onChange={(e) => setLanguage(e.target.value)}
            className="px-2 py-1 rounded-md bg-zinc-800 border border-zinc-700 text-zinc-300 text-[11px] font-medium cursor-pointer focus:outline-none focus:border-zinc-500 transition-colors h-7"
            aria-label="Select language"
          >
            {languages.map((lang) => (
              <option key={lang.id} value={lang.name}>
                {formatLangName(lang.name)}
              </option>
            ))}
          </select>

          {/* Divider */}
          <div className="w-px h-4 bg-zinc-800 mx-1" />

          {/* Stdin Toggle */}
          <button
            onClick={() => setShowStdin(!showStdin)}
            className={`flex items-center gap-1.5 px-2 py-1 rounded-md transition-all text-[11px] font-medium h-7 ${
              showStdin
                ? "bg-cyan-500/15 text-cyan-400 border border-cyan-500/25"
                : "text-zinc-500 hover:text-zinc-300 hover:bg-zinc-800 border border-transparent"
            }`}
            title="Toggle stdin input"
            aria-label="Toggle stdin"
            aria-pressed={showStdin}
          >
            <Keyboard size={13} />
            <span className="hidden md:inline">Input</span>
          </button>

          {/* Copy */}
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-2 py-1 rounded-md text-zinc-500 hover:text-zinc-300 hover:bg-zinc-800 transition-all text-[11px] font-medium h-7 border border-transparent"
            title="Copy code"
            aria-label="Copy code"
          >
            <Copy size={13} />
          </button>

          {/* Save */}
          <button
            onClick={handleSave}
            className="flex items-center gap-1.5 px-2 py-1 rounded-md text-zinc-500 hover:text-zinc-300 hover:bg-zinc-800 transition-all text-[11px] font-medium h-7 border border-transparent"
            title="Save"
            aria-label="Save file"
          >
            <Save size={13} />
          </button>

          {/* Divider */}
          <div className="w-px h-4 bg-zinc-800 mx-1" />

          {/* Run — Primary action */}
          <button
            onClick={() => handleExecute()}
            disabled={isExecuting}
            className="flex items-center gap-1.5 px-3 py-1 rounded-md bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 disabled:cursor-not-allowed text-white transition-all text-[11px] font-semibold h-7"
            title="Run code (Ctrl+Enter)"
            aria-label="Run code"
          >
            {isExecuting ? (
              <Loader2 size={13} className="animate-spin" />
            ) : (
              <Play size={12} fill="currentColor" />
            )}
            Run
          </button>

          {/* Divider */}
          <div className="w-px h-4 bg-zinc-800 mx-1" />

          {/* AI Generate */}
          <button
            onClick={() => setShowGenerator(true)}
            className="flex items-center gap-1.5 px-2 py-1 rounded-md text-purple-400/70 hover:text-purple-400 hover:bg-purple-500/10 transition-all text-[11px] font-medium h-7 border border-transparent"
            title="AI Code Generator"
            aria-label="AI Code Generator"
          >
            <Sparkles size={13} />
            <span className="hidden lg:inline">Generate</span>
          </button>

          {/* Ask AI */}
          <button
            onClick={() => onOpenAI?.()}
            className="flex items-center gap-1.5 px-2 py-1 rounded-md text-amber-400/70 hover:text-amber-400 hover:bg-amber-500/10 transition-all text-[11px] font-medium h-7 border border-transparent"
            title="Ask AI for help"
            aria-label="Ask AI"
          >
            <Brain size={13} />
            <span className="hidden lg:inline">Ask AI</span>
            {selectedCode && (
              <span className="text-[9px] text-zinc-600 hidden xl:inline">({selectedCode.length})</span>
            )}
          </button>
        </div>
      </div>

      {/* ── Main Content: Editor + Panels ── */}
      <div className="flex-1 flex flex-col min-h-0 p-3 gap-2">
        {/* Editor */}
        <div className="flex-1 min-h-0 flex flex-col bg-zinc-900 rounded-lg border border-zinc-800 overflow-hidden">
          <Editor
            height="100%"
            language={language}
            value={editorContent}
            onChange={handleContentChange}
            onMount={handleEditorMount}
            theme="vs-dark"
            loading={
              <div className="flex-1 flex items-center justify-center bg-zinc-900">
                <Loader2 size={24} className="animate-spin text-zinc-600" />
              </div>
            }
            options={{
              minimap: { enabled: true, maxColumn: 80, renderCharacters: false },
              wordWrap: "on",
              formatOnPaste: true,
              formatOnType: true,
              tabSize: 2,
              fontSize: 14,
              lineHeight: 22,
              fontFamily: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', 'Consolas', monospace",
              fontLigatures: true,
              automaticLayout: true,
              smoothScrolling: true,
              cursorBlinking: "smooth",
              cursorSmoothCaretAnimation: "on",
              cursorStyle: "line",
              padding: { top: 12, bottom: 12 },
              renderLineHighlight: "all",
              renderLineHighlightOnlyWhenFocus: false,
              currentLineHighlight: "gutter",
              selectionHighlight: true,
              occurrencesHighlight: "singleFile",
              bracketPairColorization: { enabled: true },
              guides: { bracketPairs: true, indentation: true },
              suggest: {
                showMethods: true,
                showFunctions: true,
                showConstructors: true,
                showFields: true,
                showVariables: true,
                showClasses: true,
                showStructs: true,
                showInterfaces: true,
                showModules: true,
                showProperties: true,
                showEvents: true,
                showOperators: true,
                showUnits: true,
                showValues: true,
                showConstants: true,
                showEnums: true,
                showEnumMembers: true,
                showKeywords: true,
                showWords: true,
                showColors: true,
                showFiles: true,
                showReferences: true,
                showFolders: true,
                showTypeParameters: true,
                showSnippets: true,
              },
              quickSuggestions: { other: true, comments: false, strings: false },
              parameterHints: { enabled: true },
              suggestSelection: "first",
              tabCompletion: "on",
              wordBasedSuggestions: "off",
              mouseWheelZoom: true,
              scrollbar: {
                verticalScrollbarSize: 8,
                horizontalScrollbarSize: 8,
                verticalSliderSize: 8,
              },
              overviewRulerLanes: 0,
              hideCursorInOverviewRuler: true,
              renderWhitespace: "selection",
            }}
          />
        </div>

        {/* Stdin Panel */}
        {showStdin && (
          <div className="shrink-0 bg-zinc-900 rounded-lg border border-zinc-800 overflow-hidden">
            <div className="flex items-center justify-between px-3 py-1.5 bg-zinc-800/60 border-b border-zinc-800">
              <div className="flex items-center gap-2">
                <Keyboard size={12} className="text-zinc-500" />
                <span className="text-[11px] font-medium text-zinc-400">Standard Input</span>
                {stdinInput.length > 0 && (
                  <span className="text-[10px] text-zinc-600 font-mono">{stdinInput.length} chars</span>
                )}
              </div>
              <div className="flex items-center gap-1">
                {stdinInput.length > 0 && (
                  <button
                    onClick={handleClearStdin}
                    className="p-1 rounded text-zinc-600 hover:text-zinc-300 hover:bg-zinc-700/50 transition-colors"
                    title="Clear input"
                    aria-label="Clear input"
                  >
                    <RotateCcw size={12} />
                  </button>
                )}
                <button
                  onClick={() => setShowStdin(false)}
                  className="p-1 rounded text-zinc-600 hover:text-zinc-300 hover:bg-zinc-700/50 transition-colors"
                  title="Close stdin"
                  aria-label="Close stdin panel"
                >
                  <X size={12} />
                </button>
              </div>
            </div>
            <textarea
              ref={stdinRef}
              value={stdinInput}
              onChange={(e) => setStdinInput(e.target.value)}
              placeholder="Enter input for your program..."
              className="w-full bg-zinc-900 text-emerald-400/90 font-mono text-[13px] leading-relaxed p-3 resize-none focus:outline-none border-none placeholder:text-zinc-700"
              rows={4}
              spellCheck={false}
              aria-label="Standard input"
            />
          </div>
        )}

        {/* Terminal Output */}
        {showTerminal && (
          <div className="shrink-0">
            <Terminal
              output={terminalOutput}
              error={terminalError}
              isLoading={isExecuting}
              onClose={() => setShowTerminal(false)}
              executionTime={executionTime}
              exitCode={exitCode}
              memory={memory}
            />
          </div>
        )}
      </div>

      {/* Code Generator Modal */}
      <CodeGenerator
        isOpen={showGenerator}
        onClose={() => setShowGenerator(false)}
        onInsertCode={handleInsertGeneratedCode}
      />
    </div>
  );
}

export default CodeEditor;
