import {
  Copy,
  Save,
  Play,
  Brain,
  FileCode,
  Loader2,
  Sparkles,
  Keyboard,
  X,
  RotateCcw,
} from "lucide-react";
import { useState, useEffect, useRef } from "react";
import Editor from "@monaco-editor/react";
import Terminal from "./Terminal";
import CodeGenerator from "./CodeGenerator";
import { executeCode, fetchLanguages } from "../../services/codeAPI";
import { getCompletion } from "../../services/aiAPI";
import { useToast } from "../../context/ToastContext";
import "./Terminal.css";

const detectLanguage = (filename) => {
  if (!filename) return "javascript";
  const ext = filename.split(".").pop()?.toLowerCase();
  const map = {
    js: "javascript", jsx: "javascript", ts: "typescript", tsx: "typescript",
    py: "python", java: "java", cpp: "cpp", c: "c", cs: "csharp",
    rb: "ruby", go: "go", rs: "rust", php: "php", swift: "swift",
    kt: "kotlin", sql: "sql", html: "html", css: "css", scss: "scss",
    json: "json", xml: "xml", yaml: "yaml", yml: "yaml", md: "markdown",
    sh: "shell", bash: "shell",
  };
  return map[ext] || "javascript";
};

const formatLangName = (name) => {
  if (!name) return "";
  return name.replace(/\s*\(.*\)\s*/, "").trim();
};

function CodeEditor({ activeFile, project, onContentChange, onOpenAI, runTrigger }) {
  const [isSaved, setIsSaved] = useState(true);
  const [editorContent, setEditorContent] = useState("");
  const [language, setLanguage] = useState("javascript");
  const [selectedCode, setSelectedCode] = useState("");
  const [showTerminal, setShowTerminal] = useState(false);
  const [terminalOutput, setTerminalOutput] = useState("");
  const [terminalError, setTerminalError] = useState("");
  const [isExecuting, setIsExecuting] = useState(false);
  const [executionTime, setExecutionTime] = useState(0);
  const [exitCode, setExitCode] = useState(null);
  const [memory, setMemory] = useState(null);
  const [isCompleting, setIsCompleting] = useState(false);
  const [showGenerator, setShowGenerator] = useState(false);
  const [stdinInput, setStdinInput] = useState("");
  const [showStdin, setShowStdin] = useState(false);
  const [languages, setLanguages] = useState([]);
  const [runCount, setRunCount] = useState(0);
  const editorRef = useRef(null);
  const stdinRef = useRef(null);
  const { toast } = useToast();

  useEffect(() => { fetchLanguages().then(setLanguages); }, []);

  useEffect(() => {
    if (runTrigger > 0 && project?.files) {
      const mainFile = project.files.find((f) => f.isMain);
      if (mainFile) {
        const mainLang = detectLanguage(mainFile.name);
        setLanguage(mainLang);
        setEditorContent(mainFile.content);
        handleExecute(mainFile.content, mainLang);
      } else {
        toast.warning("No main file set. Right-click a file in the explorer and set it as main.");
      }
    }
  }, [runTrigger]);

  useEffect(() => {
    if (activeFile) {
      setEditorContent(activeFile.content);
      setLanguage(detectLanguage(activeFile.name));
      setIsSaved(true);
      setSelectedCode("");
    }
  }, [activeFile]);

  const handleContentChange = (newContent) => {
    if (newContent !== undefined) {
      setEditorContent(newContent);
      setIsSaved(false);
      onContentChange(newContent);
      setIsSaved(true);
    }
  };

  const handleInsertGeneratedCode = (code) => {
    setEditorContent(code);
    onContentChange(code);
    setIsSaved(false);
  };

  const handleEditorMount = (editor, monaco) => {
    editorRef.current = editor;
    editor.onDidChangeCursorSelection((e) => {
      const selection = editor.getModel().getValueInRange(e.selection);
      setSelectedCode(selection || "");
    });
    monaco.languages.registerCompletionItemProvider(language, {
      triggerCharacters: [".", "(", "{", "[", " ", "\n"],
      provideCompletionItems: async (model, position) => {
        setIsCompleting(true);
        const textUntil = model.getValueInRange({ startLineNumber: 1, startColumn: 1, endLineNumber: position.lineNumber, endColumn: position.column });
        const textAfter = model.getValueInRange({ startLineNumber: position.lineNumber, startColumn: position.column, endLineNumber: model.getLineCount(), endColumn: model.getLineMaxColumn(model.getLineCount()) });
        try {
          const result = await getCompletion(model.getValue(), language, textUntil, textAfter);
          if (result.success && result.completion) {
            return { suggestions: [{ label: "ai-completion", kind: monaco.languages.CompletionItemKind.Snippet, insertText: result.completion, insertTextRules: monaco.languages.CompletionItemInsertTextRule.None, detail: "AI Suggestion", documentation: "Generated by ZecoAI", range: { startLineNumber: position.lineNumber, startColumn: position.column, endLineNumber: position.lineNumber, endColumn: position.column } }] };
          }
        } catch (err) { console.error("AI completion failed:", err); }
        finally { setIsCompleting(false); }
        return { suggestions: [] };
      },
    });
  };

  const handleExecute = async (code, lang) => {
    const codeToRun = code || editorContent;
    const langToUse = lang || language;
    if (!codeToRun.trim()) { toast.warning("No code to execute"); return; }
    setShowTerminal(true);
    setIsExecuting(true);
    setTerminalOutput(""); setTerminalError(""); setExecutionTime(0); setExitCode(null); setMemory(null);
    const startTime = Date.now();
    try {
      const result = await executeCode(codeToRun, langToUse, stdinInput);
      setExecutionTime(((Date.now() - startTime) / 1000).toFixed(2));
      setExitCode(result.exitCode); setMemory(result.memory); setRunCount((c) => c + 1);
      if (result.success) { setTerminalOutput(result.output || "Code executed successfully with no output"); setTerminalError(""); }
      else { setTerminalError(result.error || "Execution failed"); setTerminalOutput(result.output || ""); }
    } catch (err) { setTerminalError(err.message || "Unknown error occurred"); setTerminalOutput(""); }
    finally { setIsExecuting(false); }
  };

  const handleCopy = () => navigator.clipboard.writeText(editorContent);
  const handleSave = () => setIsSaved(true);
  const handleClearStdin = () => { setStdinInput(""); stdinRef.current?.focus(); };

  if (!activeFile) {
    return (
      <div className="flex-1 flex items-center justify-center" style={{ backgroundColor: "var(--bg-primary)" }}>
        <div className="text-center">
          <FileCode size={48} className="mx-auto mb-3" style={{ color: "var(--text-tertiary)", opacity: 0.4 }} />
          <p className="text-sm font-medium" style={{ color: "var(--text-tertiary)" }}>No file selected</p>
          <p className="text-xs mt-1" style={{ color: "var(--text-tertiary)", opacity: 0.6 }}>Choose a file from the explorer</p>
        </div>
      </div>
    );
  }

  const t = {
    bg: "var(--bg-primary)",
    bg2: "var(--bg-secondary)",
    bg3: "var(--bg-tertiary)",
    text: "var(--text-primary)",
    text2: "var(--text-secondary)",
    text3: "var(--text-tertiary)",
    border: "var(--border)",
    borderStrong: "var(--border-strong)",
    accent: "var(--accent)",
  };

  return (
    <div className="flex-1 flex flex-col min-h-0 overflow-hidden">
      {/* ── Toolbar ── */}
      <div
        className="h-11 min-h-[44px] shrink-0 px-4 flex items-center justify-between gap-3"
        style={{ borderBottom: `1px solid ${t.border}`, backgroundColor: t.bg }}
      >
        {/* Left: File info */}
        <div className="flex items-center gap-2.5 min-w-0">
          <FileCode size={15} className="shrink-0" style={{ color: t.text3 }} />
          <span className="text-[13px] font-semibold truncate" style={{ color: t.text }}>{activeFile.name}</span>
          {!isSaved && <span className="w-1.5 h-1.5 rounded-full bg-amber-400 shrink-0" />}
          <span className="text-[11px] hidden sm:inline" style={{ color: t.text3 }}>/ {project?.name}</span>
        </div>

        {/* Right: Actions */}
        <div className="flex items-center gap-1">
          {isCompleting && (
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[11px] font-medium mr-1" style={{ backgroundColor: "var(--accent-light)", color: "var(--accent)" }}>
              <Loader2 size={12} className="animate-spin" />
              <span className="hidden md:inline">AI...</span>
            </div>
          )}

          <select
            value={language}
            onChange={(e) => setLanguage(e.target.value)}
            className="px-2 py-1 rounded-md text-[11px] font-medium cursor-pointer focus:outline-none transition-colors h-7"
            style={{ backgroundColor: t.bg3, border: `1px solid ${t.border}`, color: t.text2 }}
            aria-label="Select language"
          >
            {languages.map((lang) => (
              <option key={lang.id} value={lang.name}>{formatLangName(lang.name)}</option>
            ))}
          </select>

          <div className="w-px h-4 mx-1" style={{ backgroundColor: t.border }} />

          <button
            onClick={() => setShowStdin(!showStdin)}
            className="flex items-center gap-1.5 px-2 py-1 rounded-md transition-all text-[11px] font-medium h-7"
            style={{
              backgroundColor: showStdin ? "var(--accent-light)" : "transparent",
              color: showStdin ? "var(--accent)" : t.text3,
              border: showStdin ? `1px solid var(--accent)` : "1px solid transparent",
            }}
            title="Toggle stdin input"
          >
            <Keyboard size={13} />
            <span className="hidden md:inline">Input</span>
          </button>

          <button onClick={handleCopy} className="flex items-center gap-1.5 px-2 py-1 rounded-md transition-all text-[11px] font-medium h-7" style={{ color: t.text3 }} title="Copy code">
            <Copy size={13} />
          </button>

          <button onClick={handleSave} className="flex items-center gap-1.5 px-2 py-1 rounded-md transition-all text-[11px] font-medium h-7" style={{ color: t.text3 }} title="Save">
            <Save size={13} />
          </button>

          <div className="w-px h-4 mx-1" style={{ backgroundColor: t.border }} />

          <button
            onClick={() => handleExecute()}
            disabled={isExecuting}
            className="flex items-center gap-1.5 px-3 py-1 rounded-md disabled:opacity-50 disabled:cursor-not-allowed text-white transition-all text-[11px] font-semibold h-7"
            style={{ backgroundColor: "#10b981" }}
            title="Run code"
          >
            {isExecuting ? <Loader2 size={13} className="animate-spin" /> : <Play size={12} fill="currentColor" />}
            Run
          </button>

          <div className="w-px h-4 mx-1" style={{ backgroundColor: t.border }} />

          <button onClick={() => setShowGenerator(true)} className="flex items-center gap-1.5 px-2 py-1 rounded-md transition-all text-[11px] font-medium h-7" style={{ color: "#a78bfa" }} title="AI Code Generator">
            <Sparkles size={13} />
            <span className="hidden lg:inline">Generate</span>
          </button>

          <button onClick={() => onOpenAI?.()} className="flex items-center gap-1.5 px-2 py-1 rounded-md transition-all text-[11px] font-medium h-7" style={{ color: "#fbbf24" }} title="Ask AI">
            <Brain size={13} />
            <span className="hidden lg:inline">Ask AI</span>
          </button>
        </div>
      </div>

      {/* ── Editor + Panels ── */}
      <div className="flex-1 flex flex-col min-h-0 p-3 gap-2" style={{ backgroundColor: t.bg }}>
        {/* Editor */}
        <div className="flex-1 min-h-0 flex flex-col rounded-lg overflow-hidden" style={{ backgroundColor: t.bg2, border: `1px solid ${t.border}` }}>
          <Editor
            height="100%"
            language={language}
            value={editorContent}
            onChange={handleContentChange}
            onMount={handleEditorMount}
            theme="vs-dark"
            loading={
              <div className="flex-1 flex items-center justify-center" style={{ backgroundColor: t.bg2 }}>
                <Loader2 size={24} className="animate-spin" style={{ color: t.text3 }} />
              </div>
            }
            options={{
              minimap: { enabled: true, maxColumn: 80, renderCharacters: false },
              wordWrap: "on", formatOnPaste: true, formatOnType: true,
              tabSize: 2, fontSize: 14, lineHeight: 22,
              fontFamily: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', 'Consolas', monospace",
              fontLigatures: true, automaticLayout: true, smoothScrolling: true,
              cursorBlinking: "smooth", cursorSmoothCaretAnimation: "on", cursorStyle: "line",
              padding: { top: 12, bottom: 12 },
              renderLineHighlight: "all", renderLineHighlightOnlyWhenFocus: false,
              currentLineHighlight: "gutter", selectionHighlight: true,
              occurrencesHighlight: "singleFile", bracketPairColorization: { enabled: true },
              guides: { bracketPairs: true, indentation: true },
              suggest: { showMethods: true, showFunctions: true, showConstructors: true, showFields: true, showVariables: true, showClasses: true, showStructs: true, showInterfaces: true, showModules: true, showProperties: true, showEvents: true, showOperators: true, showUnits: true, showValues: true, showConstants: true, showEnums: true, showEnumMembers: true, showKeywords: true, showWords: true, showColors: true, showFiles: true, showReferences: true, showFolders: true, showTypeParameters: true, showSnippets: true },
              quickSuggestions: { other: true, comments: false, strings: false },
              parameterHints: { enabled: true }, suggestSelection: "first",
              tabCompletion: "on", wordBasedSuggestions: "off", mouseWheelZoom: true,
              scrollbar: { verticalScrollbarSize: 8, horizontalScrollbarSize: 8, verticalSliderSize: 8 },
              overviewRulerLanes: 0, hideCursorInOverviewRuler: true, renderWhitespace: "selection",
            }}
          />
        </div>

        {/* Stdin Panel */}
        {showStdin && (
          <div className="shrink-0 rounded-lg overflow-hidden" style={{ backgroundColor: t.bg2, border: `1px solid ${t.border}` }}>
            <div className="flex items-center justify-between px-3 py-1.5" style={{ backgroundColor: t.bg3, borderBottom: `1px solid ${t.border}` }}>
              <div className="flex items-center gap-2">
                <Keyboard size={12} style={{ color: t.text3 }} />
                <span className="text-[11px] font-medium" style={{ color: t.text2 }}>Standard Input</span>
                {stdinInput.length > 0 && <span className="text-[10px] font-mono" style={{ color: t.text3 }}>{stdinInput.length} chars</span>}
              </div>
              <div className="flex items-center gap-1">
                {stdinInput.length > 0 && (
                  <button onClick={handleClearStdin} className="p-1 rounded transition-colors" style={{ color: t.text3 }} title="Clear input">
                    <RotateCcw size={12} />
                  </button>
                )}
                <button onClick={() => setShowStdin(false)} className="p-1 rounded transition-colors" style={{ color: t.text3 }} title="Close stdin">
                  <X size={12} />
                </button>
              </div>
            </div>
            <textarea
              ref={stdinRef}
              value={stdinInput}
              onChange={(e) => setStdinInput(e.target.value)}
              placeholder="Enter input for your program..."
              className="w-full font-mono text-[13px] leading-relaxed p-3 resize-none focus:outline-none border-none"
              style={{ backgroundColor: t.bg2, color: "#34d399" }}
              rows={4}
              spellCheck={false}
            />
          </div>
        )}

        {/* Terminal Output */}
        {showTerminal && (
          <div className="shrink-0">
            <Terminal
              output={terminalOutput}
              error={terminalError}
              isLoading={isExecuting}
              onClose={() => setShowTerminal(false)}
              executionTime={executionTime}
              exitCode={exitCode}
              memory={memory}
            />
          </div>
        )}
      </div>

      <CodeGenerator isOpen={showGenerator} onClose={() => setShowGenerator(false)} onInsertCode={handleInsertGeneratedCode} />
    </div>
  );
}

export default CodeEditor;
